name: lawndart
version: 0.10.0
author: Seth Ladd <sethladd@gmail.com>
description: An easier way to access storage APIs in the browser.
homepage: https://github.com/sethladd/lawndart
documentation: http://sethladd.github.com/lawndart/

environment:
  sdk: '>=2.1.1-dev <3.0.0'

dev_dependencies:
  build_runner: ^1.2.7
  build_test: ^0.10.3
  build_web_compilers: ^1.1.0
  test: ^1.5.0


