name: lawndart
version: 0.11.0
description: An easier way to access storage APIs in the browser.

environment:
  sdk: ^3.5.0

dependencies:
  web: ^1.1.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  test: any
